"""add session user_id created_at index.

Revision ID: 21d003b452d2
Revises: b25d38b0cd7c
Create Date: 2026-06-21 00:40:02.262370

"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '21d003b452d2'
down_revision: Union[str, Sequence[str], None] = 'b25d38b0cd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_session_user_created', 'session', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_user_created', table_name='session')
    # ### end Alembic commands ###
